Series

In [3]:
import pandas as pd
data=pd.Series([11,10,340,23,13])               # by default index is 0,1,2,....
data

0     11
1     10
2    340
3     23
4     13
dtype: int64

In [4]:
data=[11,10,340,23,13]                               #changes the index of the series
l=pd.Series(data,index=["a","b","c","d","e"])
l

a     11
b     10
c    340
d     23
e     13
dtype: int64

In [5]:
l.loc["a"]      #returns the value at that location

np.int64(11)

In [6]:
l.iloc[3]             #returns the value at that index location

np.int64(23)

In [7]:
l[l>200]             #prints the value in l that is greater than 200

c    340
dtype: int64

DataFrames

In [8]:
data = {                                        
    "Name": ["Ram", "Hari", "Sita"],
    "Age": [20, 21, 22],
    "City": ["Pokhara", "Kathmandu", "Butwal"]
}                                                       #Treats each dictionary as a column

df = pd.DataFrame(data)
df

   Name  Age       City
0   Ram   20    Pokhara
1  Hari   21  Kathmandu
2  Sita   22     Butwal

In [9]:
df.loc[2]             #prints all the information related to the index

Name      Sita
Age         22
City    Butwal
Name: 2, dtype: object

In [10]:
df["Job"]=["Cook","Cashier","Teacher"]  #add new column
df

   Name  Age       City      Job
0   Ram   20    Pokhara     Cook
1  Hari   21  Kathmandu  Cashier
2  Sita   22     Butwal  Teacher

In [11]:
new_row=pd.DataFrame([{"Name":"Prasiddha","Age":18,"City":"Pokhara","Job":"Student"}],index=[3])
df=pd.concat([df, new_row])       #add new row
df

        Name  Age       City      Job
0        Ram   20    Pokhara     Cook
1       Hari   21  Kathmandu  Cashier
2       Sita   22     Butwal  Teacher
3  Prasiddha   18    Pokhara  Student

In [12]:
#LOAD DATA
df=pd.read_csv("python.csv")
df

    StudentID             Name   Age  Gender              Department  Marks
0         101     Aarav Sharma   NaN    Male    Computer Engineering   78.0
1         102       Sita Thapa  19.0  Female             Electronics   85.0
2         103     Rohan Gurung  21.0    Male                     NaN   67.0
3         104      Priya Karki  20.0  Female  Information Technology   90.0
4         105         Nabin BK  22.0    Male  Mechanical Engineering   74.0
5         106       Anisha Rai  19.0  Female       Civil Engineering   88.0
6         107   Samir Shrestha  21.0    Male    Computer Engineering   81.0
7         108     Ritika Joshi  20.0  Female             Electronics   79.0
8         109        Bikash KC  23.0    Male       Civil Engineering   72.0
9         110  Asmita Adhikari  18.0  Female    Computer Engineering   95.0
10        111      Suman Thapa  20.0    Male  Mechanical Engineering   69.0
11        112    Nisha Koirala  22.0  Female            Architecture   84.0
12        113     Rabin Gurung  21.0    Male  Information Technology   76.0
13        114  Pooja Chaudhary  19.0  Female       Civil Engineering   80.0
14        115       Deepak Oli  20.0    Male             Electronics   73.0
15        116   Manisha Sharma  21.0  Female    Computer Engineering   92.0
16        117     Ritesh Yadav  22.0    Male  Mechanical Engineering   70.0
17        118     Kabita Thapa  20.0  Female            Architecture   87.0
18        119      Saroj Bista  23.0    Male       Civil Engineering   75.0
19        120     Sneha Poudel  18.0  Female  Information Technology   89.0
20        121        Ajay Rana  21.0    Male    Computer Engineering   77.0
21        122    Roshani Magar  20.0  Female             Electronics   83.0
22        123    Prakash Karki  22.0    Male       Civil Engineering   68.0
23        124     Alina Gurung  19.0  Female    Computer Engineering   91.0
24        125    Bibek Acharya  20.0    Male            Architecture   82.0
25        126        Sunita BK   NaN  Female  Mechanical Engineering   65.0
26        127       Arjun Lama  21.0    Male             Electronics    NaN

In [13]:
#SELECTION/EXPLORE DATA
df.head()                     #view the first five rows

   StudentID          Name   Age  Gender              Department  Marks
0        101  Aarav Sharma   NaN    Male    Computer Engineering   78.0
1        102    Sita Thapa  19.0  Female             Electronics   85.0
2        103  Rohan Gurung  21.0    Male                     NaN   67.0
3        104   Priya Karki  20.0  Female  Information Technology   90.0
4        105      Nabin BK  22.0    Male  Mechanical Engineering   74.0

In [14]:
df.tail()          #view the last 5 rows

    StudentID           Name   Age  Gender              Department  Marks
22        123  Prakash Karki  22.0    Male       Civil Engineering   68.0
23        124   Alina Gurung  19.0  Female    Computer Engineering   91.0
24        125  Bibek Acharya  20.0    Male            Architecture   82.0
25        126      Sunita BK   NaN  Female  Mechanical Engineering   65.0
26        127     Arjun Lama  21.0    Male             Electronics    NaN

In [15]:
df.info()             #display dataset information

<class 'pandas.DataFrame'>
RangeIndex: 27 entries, 0 to 26
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   StudentID   27 non-null     int64
 1   Name        27 non-null     str
 2   Age         25 non-null     float64
 3   Gender      27 non-null     str
 4   Department  26 non-null     str
 5   Marks       26 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 1.4 KB

In [16]:
df.describe()                  #display summary statistics

        StudentID        Age      Marks
count   27.000000  25.000000  26.000000
mean   114.000000  20.480000  79.615385
std      7.937254   1.388044   8.480929
min    101.000000  18.000000  65.000000
25%    107.500000  20.000000  73.250000
50%    114.000000  20.000000  79.500000
75%    120.500000  21.000000  86.500000
max    127.000000  23.000000  95.000000

In [17]:
df.columns              #display columns name

Index(['StudentID', 'Name', 'Age', 'Gender', 'Department', 'Marks'], dtype='str')

In [18]:
df.shape              #30 rows and 5 columns

(27, 6)

In [19]:
 #CLEAN DATA                   #checks the missing values
df.isnull().sum()

StudentID     0
Name          0
Age           2
Gender        0
Department    1
Marks         1
dtype: int64

In [20]:
 df.fillna("None")                #fills the missing value

    StudentID             Name   Age  Gender              Department Marks
0         101     Aarav Sharma  None    Male    Computer Engineering  78.0
1         102       Sita Thapa  19.0  Female             Electronics  85.0
2         103     Rohan Gurung  21.0    Male                    None  67.0
3         104      Priya Karki  20.0  Female  Information Technology  90.0
4         105         Nabin BK  22.0    Male  Mechanical Engineering  74.0
5         106       Anisha Rai  19.0  Female       Civil Engineering  88.0
6         107   Samir Shrestha  21.0    Male    Computer Engineering  81.0
7         108     Ritika Joshi  20.0  Female             Electronics  79.0
8         109        Bikash KC  23.0    Male       Civil Engineering  72.0
9         110  Asmita Adhikari  18.0  Female    Computer Engineering  95.0
10        111      Suman Thapa  20.0    Male  Mechanical Engineering  69.0
11        112    Nisha Koirala  22.0  Female            Architecture  84.0
12        113     Rabin Gurung  21.0    Male  Information Technology  76.0
13        114  Pooja Chaudhary  19.0  Female       Civil Engineering  80.0
14        115       Deepak Oli  20.0    Male             Electronics  73.0
15        116   Manisha Sharma  21.0  Female    Computer Engineering  92.0
16        117     Ritesh Yadav  22.0    Male  Mechanical Engineering  70.0
17        118     Kabita Thapa  20.0  Female            Architecture  87.0
18        119      Saroj Bista  23.0    Male       Civil Engineering  75.0
19        120     Sneha Poudel  18.0  Female  Information Technology  89.0
20        121        Ajay Rana  21.0    Male    Computer Engineering  77.0
21        122    Roshani Magar  20.0  Female             Electronics  83.0
22        123    Prakash Karki  22.0    Male       Civil Engineering  68.0
23        124     Alina Gurung  19.0  Female    Computer Engineering  91.0
24        125    Bibek Acharya  20.0    Male            Architecture  82.0
25        126        Sunita BK  None  Female  Mechanical Engineering  65.0
26        127       Arjun Lama  21.0    Male             Electronics  None

In [21]:
df.dropna()             #removes the rows with missing value

    StudentID             Name   Age  Gender              Department  Marks
1         102       Sita Thapa  19.0  Female             Electronics   85.0
3         104      Priya Karki  20.0  Female  Information Technology   90.0
4         105         Nabin BK  22.0    Male  Mechanical Engineering   74.0
5         106       Anisha Rai  19.0  Female       Civil Engineering   88.0
6         107   Samir Shrestha  21.0    Male    Computer Engineering   81.0
7         108     Ritika Joshi  20.0  Female             Electronics   79.0
8         109        Bikash KC  23.0    Male       Civil Engineering   72.0
9         110  Asmita Adhikari  18.0  Female    Computer Engineering   95.0
10        111      Suman Thapa  20.0    Male  Mechanical Engineering   69.0
11        112    Nisha Koirala  22.0  Female            Architecture   84.0
12        113     Rabin Gurung  21.0    Male  Information Technology   76.0
13        114  Pooja Chaudhary  19.0  Female       Civil Engineering   80.0
14        115       Deepak Oli  20.0    Male             Electronics   73.0
15        116   Manisha Sharma  21.0  Female    Computer Engineering   92.0
16        117     Ritesh Yadav  22.0    Male  Mechanical Engineering   70.0
17        118     Kabita Thapa  20.0  Female            Architecture   87.0
18        119      Saroj Bista  23.0    Male       Civil Engineering   75.0
19        120     Sneha Poudel  18.0  Female  Information Technology   89.0
20        121        Ajay Rana  21.0    Male    Computer Engineering   77.0
21        122    Roshani Magar  20.0  Female             Electronics   83.0
22        123    Prakash Karki  22.0    Male       Civil Engineering   68.0
23        124     Alina Gurung  19.0  Female    Computer Engineering   91.0
24        125    Bibek Acharya  20.0    Male            Architecture   82.0

In [22]:
df.drop_duplicates()              #remove duplicate rows

    StudentID             Name   Age  Gender              Department  Marks
0         101     Aarav Sharma   NaN    Male    Computer Engineering   78.0
1         102       Sita Thapa  19.0  Female             Electronics   85.0
2         103     Rohan Gurung  21.0    Male                     NaN   67.0
3         104      Priya Karki  20.0  Female  Information Technology   90.0
4         105         Nabin BK  22.0    Male  Mechanical Engineering   74.0
5         106       Anisha Rai  19.0  Female       Civil Engineering   88.0
6         107   Samir Shrestha  21.0    Male    Computer Engineering   81.0
7         108     Ritika Joshi  20.0  Female             Electronics   79.0
8         109        Bikash KC  23.0    Male       Civil Engineering   72.0
9         110  Asmita Adhikari  18.0  Female    Computer Engineering   95.0
10        111      Suman Thapa  20.0    Male  Mechanical Engineering   69.0
11        112    Nisha Koirala  22.0  Female            Architecture   84.0
12        113     Rabin Gurung  21.0    Male  Information Technology   76.0
13        114  Pooja Chaudhary  19.0  Female       Civil Engineering   80.0
14        115       Deepak Oli  20.0    Male             Electronics   73.0
15        116   Manisha Sharma  21.0  Female    Computer Engineering   92.0
16        117     Ritesh Yadav  22.0    Male  Mechanical Engineering   70.0
17        118     Kabita Thapa  20.0  Female            Architecture   87.0
18        119      Saroj Bista  23.0    Male       Civil Engineering   75.0
19        120     Sneha Poudel  18.0  Female  Information Technology   89.0
20        121        Ajay Rana  21.0    Male    Computer Engineering   77.0
21        122    Roshani Magar  20.0  Female             Electronics   83.0
22        123    Prakash Karki  22.0    Male       Civil Engineering   68.0
23        124     Alina Gurung  19.0  Female    Computer Engineering   91.0
24        125    Bibek Acharya  20.0    Male            Architecture   82.0
25        126        Sunita BK   NaN  Female  Mechanical Engineering   65.0
26        127       Arjun Lama  21.0    Male             Electronics    NaN

In [23]:
#ANALYZE DATA
df["Marks"].mean()     #find average marks

np.float64(79.61538461538461)

In [24]:
df["Marks"].max()             #Find maximum marks

np.float64(95.0)

In [25]:
df["Marks"].min()              #find minimum value

np.float64(65.0)

In [26]:
df["Name"].count()              #count students

np.int64(27)

In [27]:
df.sort_values(by="Marks",ascending=False)           #sort by marks

    StudentID             Name   Age  Gender              Department  Marks
9         110  Asmita Adhikari  18.0  Female    Computer Engineering   95.0
15        116   Manisha Sharma  21.0  Female    Computer Engineering   92.0
23        124     Alina Gurung  19.0  Female    Computer Engineering   91.0
3         104      Priya Karki  20.0  Female  Information Technology   90.0
19        120     Sneha Poudel  18.0  Female  Information Technology   89.0
5         106       Anisha Rai  19.0  Female       Civil Engineering   88.0
17        118     Kabita Thapa  20.0  Female            Architecture   87.0
1         102       Sita Thapa  19.0  Female             Electronics   85.0
11        112    Nisha Koirala  22.0  Female            Architecture   84.0
21        122    Roshani Magar  20.0  Female             Electronics   83.0
24        125    Bibek Acharya  20.0    Male            Architecture   82.0
6         107   Samir Shrestha  21.0    Male    Computer Engineering   81.0
13        114  Pooja Chaudhary  19.0  Female       Civil Engineering   80.0
7         108     Ritika Joshi  20.0  Female             Electronics   79.0
0         101     Aarav Sharma   NaN    Male    Computer Engineering   78.0
20        121        Ajay Rana  21.0    Male    Computer Engineering   77.0
12        113     Rabin Gurung  21.0    Male  Information Technology   76.0
18        119      Saroj Bista  23.0    Male       Civil Engineering   75.0
4         105         Nabin BK  22.0    Male  Mechanical Engineering   74.0
14        115       Deepak Oli  20.0    Male             Electronics   73.0
8         109        Bikash KC  23.0    Male       Civil Engineering   72.0
16        117     Ritesh Yadav  22.0    Male  Mechanical Engineering   70.0
10        111      Suman Thapa  20.0    Male  Mechanical Engineering   69.0
22        123    Prakash Karki  22.0    Male       Civil Engineering   68.0
2         103     Rohan Gurung  21.0    Male                     NaN   67.0
25        126        Sunita BK   NaN  Female  Mechanical Engineering   65.0
26        127       Arjun Lama  21.0    Male             Electronics    NaN

In [28]:
df[df["Marks"]>80]       #filter students with marks greater than 80

    StudentID             Name   Age  Gender              Department  Marks
1         102       Sita Thapa  19.0  Female             Electronics   85.0
3         104      Priya Karki  20.0  Female  Information Technology   90.0
5         106       Anisha Rai  19.0  Female       Civil Engineering   88.0
6         107   Samir Shrestha  21.0    Male    Computer Engineering   81.0
9         110  Asmita Adhikari  18.0  Female    Computer Engineering   95.0
11        112    Nisha Koirala  22.0  Female            Architecture   84.0
15        116   Manisha Sharma  21.0  Female    Computer Engineering   92.0
17        118     Kabita Thapa  20.0  Female            Architecture   87.0
19        120     Sneha Poudel  18.0  Female  Information Technology   89.0
21        122    Roshani Magar  20.0  Female             Electronics   83.0
23        124     Alina Gurung  19.0  Female    Computer Engineering   91.0
24        125    Bibek Acharya  20.0    Male            Architecture   82.0

In [29]:
df.groupby("Department")["Marks"].mean()         #groupby Department

Department
Architecture              84.333333
Civil Engineering         76.600000
Computer Engineering      85.666667
Electronics               80.000000
Information Technology    85.000000
Mechanical Engineering    69.500000
Name: Marks, dtype: float64